// Mocks generated by Mockito 5.4.6 from annotations
// in solo_play_application/test/feature/auth/presentations/views/terms_agreement_ui_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:solo_play_application/src/features/auth/presentation/blocs/terms_agreement_ui_bloc.dart'
    as _i4;
import 'package:solo_play_application/src/features/auth/presentation/blocs/terms_agreement_ui_event.dart'
    as _i7;
import 'package:solo_play_application/src/features/auth/presentation/blocs/terms_agreement_ui_state.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTermsAgreementUiState_0 extends _i1.SmartFake
    implements _i2.TermsAgreementUiState {
  _FakeTermsAgreementUiState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [TermsAgreementUiBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTermsAgreementUiBloc extends _i1.Mock
    implements _i4.TermsAgreementUiBloc {
  @override
  _i2.TermsAgreementUiState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTermsAgreementUiState_0(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeTermsAgreementUiState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.TermsAgreementUiState);

  @override
  _i5.Stream<_i2.TermsAgreementUiState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.TermsAgreementUiState>.empty(),
        returnValueForMissingStub:
            _i5.Stream<_i2.TermsAgreementUiState>.empty(),
      ) as _i5.Stream<_i2.TermsAgreementUiState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void onChange(_i6.Change<_i2.TermsAgreementUiState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i7.TermsAgreementUiEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i7.TermsAgreementUiEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.TermsAgreementUiState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i7.TermsAgreementUiEvent>(
    _i6.EventHandler<E, _i2.TermsAgreementUiState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i6.Transition<_i7.TermsAgreementUiEvent, _i2.TermsAgreementUiState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
